### ISSUE TITLE
想问下函数和参数之间加空格是个人习惯吗

### ISSUE THREAD

**Issue by pengzheng2** [hackape/react-for-designers#1]
function functionName (a, b) {
}
为啥看到很多人是 functionName(a, b) 这个有啥讲究吗？谢谢

**Comment by hackape** [comment]
没错，是偏好风格，不是要求。这个风格的一个主要倡导者是 feross 写的 standardjs formatter/linter 方案。

最初写这份教程时我打算用本地的 setup，其中包括了使用 standardjs。后来发现有在线编辑器可以用，就没有再教怎么 setup 了。
